# numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int32)

In [3]:
myarr[0, 1]

6

In [4]:
myarr.dtype

dtype('int32')

In [5]:
myarr[0, 1] = 45

In [6]:
myarr[0, 1]

45

**Array creation: Conversion other python structures**

In [7]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [8]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [9]:
listarray.dtype

dtype('int32')

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,4,4)

In [18]:
lspace

array([1., 2., 3., 4.])

In [19]:
emp = np.empty((4,6))

In [20]:
emp


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.78143909e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.11260144e-306, 6.89812281e-307, 2.22522596e-306]])

In [21]:
emp_like  = np.empty_like(lspace)

In [22]:
emp_like

array([1., 2., 3., 4.])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
arr  = np.arange(99)

In [27]:
arr = arr.reshape(3, 33)

In [28]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [33]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [34]:
ar.flat

In [35]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [36]:
ar.ndim

2

In [37]:
ar.size

9

In [38]:
ar.nbytes

36

In [39]:
ar.dtype

dtype('int32')

In [40]:
one = np.array([1,3,4,634,2])

In [41]:
one.argmax()

3

In [42]:
one.argmin()

0

In [43]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.argmax()

6

In [46]:
ar.argmin()

8

In [47]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [49]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [56]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [57]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [65]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 2],
       [8, 1, 0]])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5,  8],
       [15,  2,  0]])

In [67]:
ar  * ar2

array([[ 1,  4,  3],
       [16,  0, 12],
       [56,  1,  0]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [72]:
ar.sum()

29

In [73]:
ar.min()

0

In [76]:
ar.max()

7

In [78]:
type(np.where(ar>5))

tuple

In [80]:
np.count_nonzero(ar)

8

In [83]:
ar[1,2] = 0

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [85]:
import sys

In [89]:
py_ar  = [0,4,55,2]

In [90]:
np_ar = np.array(py_ar)

In [96]:
sys.getsizeof(1)*len(py_ar)

112

In [98]:
np_ar.itemsize * np_ar.size 

16

In [99]:
np_ar.tolist()

[0, 4, 55, 2]

In [100]:
sys.getsizeof(1)*len(np_ar)

112